### ISSUE TITLE
跟我的Leetcode repo好像呀哈哈

### ISSUE THREAD

**Issue by QuBenhao** [MeteorDream/Algorithm#4]
怎么没有坚持更一下Python代码

**Comment by MeteorDream** [comment]
> 怎么没有坚持更一下Python代码

哈哈，因为后面的没有写题解，加上换了IDE又没有迁移目录，这两天我重新整理下~

**Comment by QuBenhao** [comment]
> > 怎么没有坚持更一下Python代码
> 
> 
> 
> 哈哈，因为后面的没有写题解，加上换了IDE又没有迁移目录，这两天我重新整理下~

哈哈哈难怪，坐等更新了
